### ISSUE TITLE
Sponsor Button Broken

### ISSUE THREAD

**Issue by zicklag** [zackify/cli.rs#9]
Hey there, this is a great idea!

Just wanted to let you know that the sponsor button is currently broken: 
![image](https://user-images.githubusercontent.com/25393315/88732012-df9a7880-d0fc-11ea-9929-93295615cedc.png)

**Comment by zackify** [comment]
I’m pending review so hopefully any day now. 

I will close this when it’s fixed. 

The small amount of funding will go to extending the domain renewal. 

If there’s some extra, I may setup a server and use a rust based dns server instead of DigitalOcean, if anyone wants to help, just to be really rust-centric. Then maybe spend time on a good way to search through the projects or something too :D

**Comment by zackify** [comment]
Alright, its been approved
